name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0

    - name: setup
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 #2.1.5
      with:
        go-version: '1.17'

    - name: lint
      uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 #2.5.2
      with:
        only-new-issues: true
        skip-go-installation: true

    - name: vet
      run: go vet ./...
  
    - name: test
      run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

    - name: upload coverage
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b #v2.1.0

    - name: benchmark
      run: go test -bench 'BenchmarkFib' | tee output.txt

    - name: download previous benchmark data
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed #2.1.7
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: store benchmark result
      uses: benchmark-action/github-action-benchmark@b7064e06aeeb370bc6da9992de82f14aa8334089 #1.12.0
      with:
        tool: go
        output-file-path: output.txt
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true

    - name: Run build
      run: go build cmd
